# Welcome to Jekyll!
#
# Site settings
title: Di-fusão Now All
email: uni.om@aol.com

description: >- # this means to ignore newlines until "baseurl:"
  Textos que chegaram através do homem nawal,
  nahualli, arhat, tathāgata, jīvanmukti, yogi, sidha,
  Arya, Nuvem Que Passa, Cavalo de Fogo, Alex Sed Rex,
  Júlio César Guerrero, Toltecayolt, 儒 , Rú, dao, tao, 道 ,
  xamanismo guerreiro, advaita vedanta, Arya Ashta Marga,
  bhagavatam, samadhi, moksha, mukti, nirvana, satori, 悟り,
  kensho, bodhi, jnana, atma jnana, Wu, 悟 , kototama,
  言霊 , 言魂, mushin, 無心 , Wu wei,  無為 , Dainichi Nyorai,
  大日如来, ratna trayaya, chatur arya satya, sat chit ananda,
  brahman, totalidade, infinito, बुद्ध, Buddha, sanatana dharma,
  dharmapāla, Gopala, Kavi, Pir, Rishi, Muni, Dhammacakka,
  liberdade, aventura, vida longa, ॐ

# Navigation settings
navigation:
  - title: "Di-Fusão Now All"
    url: /
  - title: "About"
    url: /about/
  - title: "Posts"
    url: /posts/
  - title: "Links"
    url: /links/
  - title: "ventania"
    url: /indexes/ventania/
  # - title: "index 2"
  #   url: /indexes/index2/
  # - title: "index 3"
  #   url: /indexes/index3/
  # - title: "index 4"
  #   url: /indexes/index4/
  # - title: "index 5"
  #   url: /indexes/index5/
  # - title: "index 6"
  #   url: /indexes/index6/
  # - title: "index 7"
  #   url: /indexes/index7/
  # - title: "index 8"
  #   url: /indexes/index8/
  # - title: "index 9"
  #   url: /indexes/index9/
  # - title: "index 10"
  #   url: /indexes/index10/

# Collections
collections:
#  articles:
#    output: true
#    permalink: /textos/:path/
  indexes:
    output: true
    permalink: /indexes/:path/

# Minima theme settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://uni-om.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AztlanDon
github_username: uni-om

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
