# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Di-fusão Now All
email: uni.om@aol.com
description: >- # this means to ignore newlines until "baseurl:"
  Textos que chegaram através do homem nawal,
  nahualli, arhat, tathāgata, jīvanmukti, yogi, sidha,
  Arya, Nuvem Que Passa, Cavalo de Fogo, Alex Sed Rex,
  Júlio César Guerrero, Toltecayolt, dao, tao, 道 ,
  xamanismo guerreiro, advaita vedanta, Arya Ashta Marga,
  bhagavatam, samadhi, moksha, mukti, nirvana, satori, 悟り,
  kensho, bodhi, jnana, atma jnana, Wu, 悟 , kototama,
  言霊 , 言魂, mushin, 無心 , Wu wei,  無為 , Dainichi Nyorai,
  大日如来, ratna trayaya, chatur arya satya, budha, sat chit ananda,
  brahman, Oomoto sume oomikami, 大天主太神, sanatana dharma,
  dharmapāla, Gopala, Kavi, Pir, Rishi, Muni, Chakravartin,
  Sumera Mikoto, 天子, 天命, 天下, Dhammacakka, Prajapati, Avalokiteśvara
  liberdade, aventura, vida longa, ॐ




 # (You can edit this
 # line in _config.yml. It will appear in your document head meta (for
 # Google search results) and in your feed.xml site description.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AztlanDon
github_username:  uni-om

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  listas:
    output: true
    permalink: /lista/:path/
    menu_exclude: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
